SiteTitle: TestCentric
Logo: /img/NewTestCentricLogo.png
sass-primary: Green
PostSources: blog/*
LastUpdate: => { if (Document.ContainsKey("Updated")) return Document.GetDateTime("Updated"); return Document.GetDateTime("Published"); };
IsPost: => Outputs.FilterSources(Context.GetString("PostSources")).ContainsById(Document)
#ApiPath: tc-lite/api
#SourceFiles:
#{
#    "../tc-lite/src/tclite/*.cs",
#    "../tc-lite/src/tclite/Attributes/*.cs",
#    "../tc-lite/src/tclite/Constraints/*.cs", 
#    "../tc-lite/src/tclite/Interfaces/*.cs",
#    "../tc-lite/src/tclite/Runners/TestRunner.cs"
#}
#IncludeGlobalNamespace: false
